### ISSUE TITLE
UNABLE TO GENERATE LINK TO SHARE

### ISSUE THREAD

**Issue by ghastlyx** [caydey/ffshare#61] opened 2023-09-03 02:21 UTC
I have been unable to generate any link to share. It converts the file then goes back to the folder. Not sure of I'm doing it wrong.

**Comment by caydey** [comment] 2023-09-03 09:03
Duplicate of #62, visit there for full explanation

**Closed by caydey** 2023-09-03 09:03 UTC

**Comment by ghastlyx** [comment] 2023-09-03 09:08
Thanks for the feedback. It's working with the older version.

Regards
