### ISSUE TITLE
Interruption

### ISSUE THREAD

**Issue by idexample** [caydey/ffshare#59] opened 2023-08-21 19:40 UTC
Hi, I cannot leave it on background as even pulling down the notifications the conversion freeze and doesn't go further.
I tried everything, disabling battery optimization, and giving it permission to run in background but it stops, even leaving running without any intervention let the screen shut off and also the process abruptly ends.
On Huawei p40 
![az_recorder_20230821_203948](https://github.com/caydey/ffshare/assets/72635012/643024b6-00ea-41de-8c39-4186e1022731)

**Comment by caydey** [comment] 2023-08-27 11:43
Duplicate of #4

**Closed by caydey** 2023-08-27 11:43 UTC
Labels: duplicate
