### ISSUE TITLE
Rotating the screen fails the compression

### ISSUE THREAD

**Issue by 825i** [caydey/ffshare#32] opened 2023-01-29 00:07 UTC
If my screen rotates the compression completes immediately and gives me a corrupted file output.

OnePlus Pro 10.

**Comment by 825i** [comment] 2023-02-26 15:47
Happens also on Vivo X90 Pro+

**Comment by hackerb9** [comment] 2023-05-06 22:37
I believe this bug and #35 should be merged with #4 as they are all likely caused by the same issue.

**Comment by caydey** [comment] 2023-08-12 15:00
#58

**Closed by caydey** 2023-08-12 15:00 UTC
Labels: bug
