### ISSUE TITLE
Add save (temporary file) to internal storage option

### ISSUE THREAD

**Issue by rufuswilson** [caydey/ffshare#65] opened 2023-09-15 20:52 UTC
Hi,

I was trying to save space with my videos and I found this app which is marvelous. My current workflow is compress video, send it to nextcloud and then download it back to my mobile.

The only thing that I am missing is the possibility to save the video to the phone directly bypassing the trip to nextcloud. It could be as simple as storing the temporary file into a user defined folder.

What do you think?

Thanks

**Comment by rufuswilson** [comment] 2023-09-16 14:09
> but I use this app for saving it https://www.f-droid.org/de/packages/name.lmj001.savetodevice/

Thanks for the tip

**Comment by caydey** [comment] 2024-06-05 20:20
Closing as duplicate of #15

**Closed by caydey** 2024-06-05 20:20 UTC
Labels: duplicate
